# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
     # - name: "Upload Artifact 1.15.2"
      #  uses: actions/upload-artifact@v1
       # with:
        #  name: zh_tw-Lang-Pack+Snapshot-1.15.2-${{ github.run_number }}.zip
         # path: 1.15.2/
   #   - name: "Upload Artifact 1.12.2"
    #    uses: actions/upload-artifact@v1
     #   with:
      #    name: zh_tw-Lang-Pack+Snapshot-1.12.2-${{ github.run_number }}.zip
       #   path: 1.12.2/
      - uses: papeloto/action-zip@v1 #zipped file 1.15.2
        with:
          files: 1.15.2/
          dest: zh_tw-Lang-Pack+Snapshot-1.15.2-${{ github.run_number }}.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: Snapshot-${{ github.run_number }}
          file: ${{ github.workspace }}/zh_tw-Lang-Pack+Snapshot-1.15.2-${{ github.run_number }}.zip
          asset_name: zh_tw-Lang-Pack+Snapshot-1.15.2-${{ github.run_number }}.zip
          prerelease: true
          overwrite: true 
          boby: "版本編號:${{ github.run_number }}"
